version: "3.9"

# Start with
# docker compose -p shoppinglist up --build api

volumes:
    pgdata:
    pgadmindata:


services:
    db:
        image: timi007/shoppinglistdatabase:latest
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: my_user
            POSTGRES_PASSWORD: my_password
        volumes:
          - pgdata:/var/lib/postgresql/data

    pgadmin:
        profiles:
            - "pgadmin"
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: my_user@example.com
            PGADMIN_DEFAULT_PASSWORD: my_password
        ports:
            - "5050:80"
        depends_on:
            - db
        links:
            - "db:psqlserver"
        volumes:
          - pgadmindata:/var/lib/pgadmin

    api:
        build:
            context: .
            dockerfile: ./ShoppingListMinimal/Dockerfile
        image: timi007/shoppinglistapi:latest
        environment:
            ConnectionStrings__ShoppingList: "Host=psqlserver;Database=ShoppingList;Username=my_user;Password=my_password"
            Logging__LogLevel__Default: Information
        ports:
            - "5000:5000"
        depends_on:
            - db
        links:
            - "db:psqlserver"
  