version: "3.9"

# Start with
# docker compose -p shoppinglist up --build api -d

volumes:
    pgdata:
    pgadmindata:


services:
    db:
        image: timi007/shoppinglistdatabase:latest
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
          - pgdata:/var/lib/postgresql/data

    pgadmin:
        profiles:
            - "pgadmin"
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
        ports:
            - "${PGADMIN_PORT}:80"
        depends_on:
            - db
        links:
            - "db:psqlserver"
        volumes:
          - pgadmindata:/var/lib/pgadmin

    api:
        build:
            context: .
            dockerfile: ./ShoppingListMinimal/Dockerfile
        image: timi007/shoppinglistapi:latest
        environment:
            ConnectionStrings__ShoppingList: "Host=psqlserver;Database=ShoppingList;Username=${DB_USER};Password=${DB_PASSWORD}"
            Logging__LogLevel__Default: ${API_LOGLEVEL}
        ports:
            - "${API_PORT}:5000"
        depends_on:
            - db
        links:
            - "db:psqlserver"
  